#!/bin/sh /etc/rc.common
START=99
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /etc/sing-box/singbox-pbr-watch.sh
	procd_set_param respawn 3600 0 5
	procd_set_param stdout 0
	procd_set_param stderr 1
	procd_close_instance
}

stop() {
	ip route flush table 100 2>/dev/null
	ip rule del pref 100 2>/dev/null
}
